### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by warmdog** [wangzhenjjcn/PUBG_HACK#1]
按照步骤来的，没有任何显示/。怎么用 的

**Comment by wangzhenjjcn** [comment]
首先，你的PUBG得是默认目录，不然你将C:\Program Files (x86)\Steam\steamapps\common\PUBG\TslGame\Content\Paks改成你的安装目录下对应文件夹
其次，你要下载对应的PAK文件，具体自己查找，
然后管理员权限打开BAT，他会把BAT相同目录下PAK文件夹下的pak文件做快捷方式到PUBG的PAK文件夹下
然后你再黑屏进EC服务器的时候切出去输个数字就OK了。
话说最近PAK文件都不好用，不知道是不是真的，
