### ISSUE TITLE
How to uninstall if we need to

### ISSUE THREAD

**Issue by Puffalumps** [wangzhenjjcn/PUBG_HACK#10]
Needed to know how to uninstall this when i dont want it no more

**Comment by wangzhenjjcn** [comment]
@Puffalumps 
every time u finish this bat it uninstalled already
when u wanna use re-run it  
if u don't want the copy paks just delete the folder in driver C

**Comment by wangzhenjjcn** [comment]
@Puffalumps 

reinstall  game is ok
