### ISSUE TITLE
function

### ISSUE THREAD

**Issue by whzarthur** [wangzhenjjcn/PUBG_HACK#11]
9/5000
Zhège wàiguà yǒu shé me gōngnéng
What is the function of this plug-in

**Comment by wangzhenjjcn** [comment]
啊啊啊啊
看你pak有什么功能
It depends on your pak files

**Comment by wangzhenjjcn** [comment]
@whzarthur 
It depends on your pak files

**Comment by whzarthur** [comment]
兄弟，这外挂有没有透视啊

**Comment by wangzhenjjcn** [comment]
@whzarthur 没有

**Comment by wangzhenjjcn** [comment]
@whzarthur 
自己看pak的英文意思推测下，去墙可能有的
