### ISSUE TITLE
Just Wondering, is it still undetected ?

### ISSUE THREAD

**Issue by Bogdan11113** [wangzhenjjcn/PUBG_HACK#13]
=

**Comment by wangzhenjjcn** [comment]
@Bogdan11113 
sorry for that 
I don't know either

**Comment by wangzhenjjcn** [comment]
@Bogdan11113 
CAUTION USE AT YOUR OWN RISK

**Comment by wangzhenjjcn** [comment]
@Bogdan11113 
Only For Test Dude
All Risk In Main Server Take By Yoursel
