### ISSUE TITLE
How to use with new release TslGame-WindowsNoEditor_ui1.pak?

### ISSUE THREAD

**Issue by gonhakase** [wangzhenjjcn/PUBG_HACK#16]
after new anticheat update run bat file and Xenuine error
any updated?

**Comment by wangzhenjjcn** [comment]
working
usage：download and run bat
if dont use pls uninstall
if not work check path which pubg installed in 
if not de fault edit pak file change pubg_path settings in bat and uninstall bat

**Comment by wangzhenjjcn** [comment]
@gonhakase

**Comment by gonhakase** [comment]
@wangzhenjjcn working but play after 5-10 min error25 and closed game
thanks

**Comment by wangzhenjjcn** [comment]
@gonhakase test server only or CAUTION USE AT YOUR OWN RISK 
maybe u wanna get a ban
