### ISSUE TITLE
Cant use after 9gb update;

### ISSUE THREAD

**Issue by Unkownz** [wangzhenjjcn/PUBG_HACK#17]
Hello
First ty for your git and ur projects ! Amazing stuff.
After the 9gb update on PUBG
I cannot start with modified .paks. ( Look like there is a MD5 check )
The game no longer loads the unencrypted PAK file any update for this ?

**Comment by wangzhenjjcn** [comment]
@Unkownz  working~

**Comment by wangzhenjjcn** [comment]
@Unkownz 
Now the answer is YESSSSSSSSSS~!
