### ISSUE TITLE
友情提示

### ISSUE THREAD

**Issue by iostyle** [wangzhenjjcn/PUBG_HACK#18]
开挂司马 灵车飘逸 骨灰拌饭
程序猿还开外挂？要脸吗？
技术学习可以，请去自定义。

**Comment by wangzhenjjcn** [comment]
@iostyle 
Are you lost your mind, dude?  Or have you been in a bad life lately？
Do not impose on others what yourself do not desire to see or understanding，thanks.

**Comment by wangzhenjjcn** [comment]
@iostyle 
友情提示（比你标题更真正的友情提示）
不要和泼妇一样跑来骂街来彰显自己思想上的幼稚。
摸过千古看淡点。

**Comment by CatlovesCoco** [comment]
想学习怎么制作，因为外挂太多，所以想学做外挂来抵制外挂...
BTW, I'm a just a CSS student.

**Comment by wangzhenjjcn** [comment]
@CatlovesCoco 
主线任务前置条件未完成（CSS Student Only,Java C Cpp Cpppp Go Lua NodeJs Python AngulaJs To be Done）
不能制作，制作代码里面有。
要救公主请先完成主线任务先。

**Comment by CCint3** [comment]
@wangzhenjjcn 游戏20分钟左右，会提示客户端无响应，接着就掉线。请问这个有什么办法解决吗？

**Comment by iostyle** [comment]
竞技游戏开挂被骂就是活该，人人唾弃。
我说的很明白，技术学习可以，请去自定义，但竞技开挂，不好意思，cnm。
