### ISSUE TITLE
前辈，黑屏的时候没声音哎。。。这个最后到底是什么功能？

### ISSUE THREAD

**Issue by Junjun7** [wangzhenjjcn/PUBG_HACK#2]
黑屏的时候没声音哎。。。这个最后到底是什么功能？

**Comment by wangzhenjjcn** [comment]
首先，你的PUBG得是默认目录，不然你将C:\Program Files (x86)\Steam\steamapps\common\PUBG\TslGame\Content\Paks改成你的安装目录下对应文件夹
其次，你要下载对应的PAK文件，具体自己查找，
然后管理员权限打开BAT，他会把BAT相同目录下PAK文件夹下的pak文件做快捷方式到PUBG的PAK文件夹下
然后你再黑屏进EC服务器的时候切出去输个数字就OK了。
【最后的功能就是把做的快捷方式链接删了。。。】
话说最近PAK文件都不好用，不知道是不是真的，

**Comment by wangzhenjjcn** [comment]
现在pak貌似是有问题的会25BAN，慎用
