### ISSUE TITLE
无法运行.bat文件

### ISSUE THREAD

**Issue by TingliangZhang** [wangzhenjjcn/PUBG_HACK#5]
无法运行.bat文件
管理员模式启动后

![image](https://user-images.githubusercontent.com/32335780/35196172-6b7b9f8c-ff09-11e7-9fc1-fe9bee61ce1d.png)

是不是.bat有问题？

**Comment by wangzhenjjcn** [comment]
编码问题，下载的编码应该是ANSI编码。可能你的机器直接转译成了UTF-8

**Comment by wangzhenjjcn** [comment]
FIXed AT Last Version

**Comment by wangzhenjjcn** [comment]
兄得欸，你索，你都自道git check了，你咋不看下git的bat源码呢，很明显的编码错误问题哇~~~~

**Comment by wangzhenjjcn** [comment]
不要使用powershell，用command line cmd
然后，因为编码问题，第一个字符@可能解析错误，推荐这样，
自己建一个txt从github上拷贝代码，黏贴进去保存，然后重命名文件以bat结尾。（如果系统没显示已知扩展名，打卡即可）
然后就可以了

2018-01-22 0:16 GMT+08:00 TingliangZhang <notifications@github.com>:
