### ISSUE TITLE
how to use and I wanna know the mechanism？

### ISSUE THREAD

**Issue by IIMP** [wangzhenjjcn/PUBG_HACK#6]

**Comment by nitrogen69** [comment]
Did everything in the description (don't think i really understood what you wrote) but i tried. 
> Made a folder on desktop called "PAKS"
> Dragged bat file into the folder
> Made a new folder in the "PAKS" folder and dragged my paks in there.
> Ran the .bat file as an administrator.
> Did everything from there, but no sound occured, or anything else like that, no black screen or anything :/

**Comment by wangzhenjjcn** [comment]
I'm sorry for that these days I was busy with my work and don't give your response in time
and I have read your msg
[Made a folder on desktop called "PAKS"]
it's no need to make a folder name paks on desktop,just download and unzip it anywhere
just let the bat file and paks folder in same folder it's ok
[Ran the .bat file as an administrator.]
all right about this
[Did everything from there, but no sound occured, or anything else like that, no black screen or anything :/]
this maybe ur windows is installed in english language
this bat file have some ANSI and unicode code in it,so u can try this
1.make a new txt file on your desktop
2.open this repo and open this bat on web page
3.copy these code and paste on your new txt file and save it
4.rename the txt file and with a file name end with bat
5.paste this bat file into where ur download and unzip folder and run as administrator
If any question u can email me ,wangzhenjjcn@gmail.com
If I cannot give ur response in time dont be mad with me.
thanks

**Comment by wangzhenjjcn** [comment]
@IIMP IT CHEAT THE PAK FILES INTO MEMORY
