### ISSUE TITLE
这个外挂有什么功能？除了后坐力 透视有吗

### ISSUE THREAD

**Issue by tokenIsme** [wangzhenjjcn/PUBG_HACK#8]
WHAT IS WRONG
WHAT IS ERR INFO

**Comment by wangzhenjjcn** [comment]
自己加PAK文件就可以，如果没有的话，你翻一番zip文件。里面好像应该有的

**Comment by wangzhenjjcn** [comment]
@tokenIsme

**Comment by tokenIsme** [comment]
那个paks 里的文件 目录是 自己新建一个 还是定位到游戏目录里的paks  不太清楚这个挂的原理是什么

**Comment by wangzhenjjcn** [comment]
@tokenIsme   只要pak文件在PAKS文件夹下即可，自动的链接
原理好复杂的，不一定所有人可以理解的，理解也不一定学以致用
不要想太多
