### ISSUE TITLE
PreRelease.bat is still work

### ISSUE THREAD

**Issue by cheertung** [wangzhenjjcn/PUBG_HACK#9]
os:windows 7
PreRelease.bat is still work 
but my steam account was banned by PUBG

**Comment by wangzhenjjcn** [comment]
@cheertung 
U should Knew
PUBG_HACK CAUTION USE AT YOUR OWN RISK

**Comment by cheertung** [comment]
got it

**Comment by cheertung** [comment]
@wangzhenjjcn 
got it
